<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNewTweets($lastId){
        $query = $this->createQueryBuilder('t')
            ->where('t.id > :id')
            ->setParameter('id', $lastId)
            ->orderBy('t.id', 'ASC')
            ->getQuery();
        
        return $query->getArrayResult();
    }
}
